### ISSUE TITLE
allow yaml parselets

### ISSUE THREAD

**Issue by tycho01** [redapple/parslepy#15]
Would you take a PR adding `from_yamlstring` / `from_yamlfile`? No duplicate code needed.

**Comment by redapple** [comment]
Hi @tycho01 ,
I'd be happy to review a PR for this. I've been wanting that myself.
I haven't used parslepy much lately but I'm glad some are considering using it!

**Comment by tycho01** [comment]
Sure! I was pretty happy to find a Python version of Parsley, combines pretty well with the Scrapy ecosystem. :)
I made a PR now at #16, let me know if there's anything I can improve about it!
